# Generated by Django 5.1.1 on 2024-09-22 07:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
